sudo: required

language: node_js
dist: trusty

node_js:
  - "stable"

services:
  - docker

env:
  - DOCKER_IMAGE=rso9/frontend:0.1.4

script:
  - docker build -t "$DOCKER_IMAGE" .
  - docker run -d -p 3000:3000 "$DOCKER_IMAGE"

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
